name: smart_bus_students
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  firebase_core: 1.13.1
  cloud_firestore: 3.1.10
  firebase_auth: 3.3.11
  firebase_database: 9.0.8
  result_type: 0.1.0
  firebase_storage: 10.2.9
  cached_network_image: 3.2.0
  lottie: 1.2.2
  pin_code_fields: 7.3.0
  shared_preferences: 2.0.13
  razorpay_flutter: ^1.2.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/fonts/
  uses-material-design: true

